apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: {{.Values.app.name}}
    app.kubernetes.io/name: {{.Values.app.name}}
  name: {{.Values.app.name}}
  namespace: {{.Values.app.namespace}}
spec:
  ingressClassName: {{.Values.ingress.class}}
  rules:
  - host: {{.Values.ingress.url}}
    http:
      paths:
      - pathType: Prefix
        backend:
          service:
            name: {{.Values.app.name}}
            port:
              number: 80
        path: /       
