apiVersion: v1
kind: Service
metadata:
  name: simple-time-app
  namespace: {{ .Values.app.namespace }}
  labels:
    app.kubernetes.io/instance: simple-time-app
    app.kubernetes.io/name: simple-time-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: simple-time-app
    app.kubernetes.io/name: simple-time-app
  sessionAffinity: None
  type: ClusterIP